title: Movie Recommendation System
theme: jekyll-theme-minimal
## Connect with me
- ğŸ“§ [Email](mailto:jonathan@email.com)
- ğŸ’¼ [LinkedIn](https://linkedin.com/in/jonathan-sebastian)
- ğŸ™ [GitHub](https://github.com/sebastianmoiras)
